---
title: "Client Report - Flights: Creating New Columns"
subtitle: "Unit 2 Task 1"
author: "Justin Hair"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```



```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))

# display(df.head())
```

## QUESTION 1

1. __Create a new 'season' column.__ Define 'season' as:
    1. Winter for January, Febuary (note the mispelling), March
    1. Spring for April, May, June
    1. Summer for  July, August, September
    1. Fall for October, November, December
    1. All other rows can be assigned a value of 'Unknown' 

_No discussion needed for this question_

```{python}
winter = ['January', 'Febuary', 'March']
spring = ['April', 'May', 'June']
summer = ['July', 'August', 'September']
fall = ['October', 'November', 'December']

Q1 = df.with_columns(
  pl.when(pl.col('month').is_in(winter))
                .then(pl.lit('Winter'))
                .when(pl.col('month').is_in(spring))
                .then(pl.lit('Spring'))
                .when(pl.col('month').is_in(summer))
                .then(pl.lit('Summer'))
                .when(pl.col('month').is_in(fall))
                .then(pl.lit('Fall'))
                .otherwise(pl.lit('Unknown'))
                .alias('season')
)
# .filter(pl.col('season') == 'Unknown') # Used this to learn that there are only 18 rows where no month is given. 

# display(Q1.sample(5))

```

## QUESTION 2

1. __Divide all the columns by 1000 whose name starts with num_of.__ Be sure to first filter out rows that contain problematic values for the columns like -999 or 1500+.

_No discussion needed for this question_

```{python}
"""
I need to:
- clean num_of_delays_carrier by removing "+" or "-"
- convert num_of_delays_carrier	to a i64 from str
- chose the columns that start with num_of ('^num_of.*$')
- remove any row where there is a negative value
- divide them by 1000
"""

# remove "+" and "-" from num_of_delays_carrier
Q2 = Q1.filter(pl.col('num_of_delays_carrier').str.contains(r'^\d+$')) # the /d makes it possible to check for a "+" 

# cast num_of_delays_carrier to i64
Q2 = Q2.with_columns(pl.col('num_of_delays_carrier').cast(pl.Int64))

# chose the columns that start with num_of and remove any row where there is a negative value
Q2 = Q2.filter(
    pl.all_horizontal(pl.col('^num_of.*$') >= 0)
)

# divide them by 1000
Q2 = Q2.with_columns(
    pl.col('^num_of.*$') / 1000
)

# display(Q2.head())
```

## QUESTION 3

1. According to the BTS website, the “Weather” category only accounts for severe weather delays. Mild weather delays are not counted in the “Weather” category, but are actually included in both the “nas” and “late_aircraft” categories. __Using the columns you modified in the bullet above, your job is to create a new column that calculates the total number of flights (in 1,000's) delayed by weather (both severe and mild).__ Show your work by printing the first 5 rows of the dataset. Use these three rules for your calculations:  

    a. 100% of delayed flights in the Weather category are due to weather  
    a. 30% of all delayed flights in the "late_aircraft" category are due to weather  
    a. From April through August, 40% of delayed flights in the NAS category are due to weather. The rest of the months, the proportion rises to 65%  

_No discussion needed for this question_

```{python}
'''
Todo:
- make new column ('flight_delayed_by_weather') that consists of:
    + "num_of_delays_weather" 
    + .30 * "num_of_delays_late_aircraft"
    .when month is apr-aug .then .40 * "num_of_delays_nas" .otherwise .65 * "num_of_delays_nas"
- 
'''

Q3 = Q2.with_columns(
  flights_delayed_by_weather = pl.col('num_of_delays_weather')
  + (0.30 * pl.col('num_of_delays_late_aircraft'))
  + pl.when(pl.col('month').is_in(['April', 'May', 'June', 'July', 'August']))
        .then(0.40 * pl.col('num_of_delays_nas'))
        .otherwise(0.65 * pl.col('num_of_delays_nas'))
)

display(Q3.head(5))



```

## QUESTION 4

1. __Using the new weather variable calculated above, create a boxplot showing the distribution of flights delayed by weather for each season. Describe what you learn from this graph.__    

Based on the data, the best time to fly to avoid weather delays would be in the Spring, followed by Summer. 

```{python}
"""
Todo:
- create boxplot. x=season, y=flights_delayed_by_weather
"""

(
  ggplot(data=Q3, mapping=aes(x='flights_delayed_by_weather', y='season'))
  + geom_boxplot(outlier_alpha=0.3, outlier_shape=3, outlier_size=0.75)
)

```