---
title: "Unit 4 Stretch"
author: "Justin Hair"
format:
  html:
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
---

```{python}
# Import libraries
import polars as pl
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.inspection import permutation_importance
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score


# import dataframes
url_ml = "https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_ml/dwellings_ml.csv"
url_neighborhoods = "https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_neighborhoods_ml/dwellings_neighborhoods_ml.csv"

df_ml = pl.read_csv(url_ml)
df_neighborhoods = pl.read_csv(url_neighborhoods)
```

# Stretch Questions

## Question 1
Join the dwellings_neighborhoods_ml.csv data to the dwelling_ml.csv on the parcel column to create a new dataset. Duplicate the code for the model you recommended in the previous task above and update it to use this data. Explain the differences and if this changes the model you recomend to the Client. 

So with this newly added data, the accuracy of the model does improve and thus I would recommend this newer model. While it does use the exact same machine learning model, we have more input data and so the response is better.

```{python}
df_joined = df_ml.join(df_neighborhoods, on='parcel', how='left')
```

```{python}

# make a list of all the nieghborhood columns 
nbhd_cols = [c for c in df_joined.columns if c.startswith('nbhd_')]

feature_columns = [
    'quality_C', 
    'gartype_Att', 
    'arcstyle_ONE-STORY', 
    'livearea',
    'stories', 
    'numbaths', 
    'sprice', 
    'basement',
    'arcstyle_TWO-STORY', 
    'quality_B', 
    'finbsmnt'
] + nbhd_cols

x = df_joined.select(feature_columns)
y = df_joined.select('before1980')

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model = XGBClassifier(random_state=42)
model.fit(x_train, y_train)
pred = model.predict(x_test)

print(metrics.classification_report(y_test, pred))


result = permutation_importance(model, x_test, y_test, n_repeats=10, random_state=42)
importance = pl.DataFrame({
    "feature": feature_columns,
    "importance": result.importances_mean,
}).sort("importance", descending=True)

print(importance)

```

## Question 2
Can you build a model that predicts the year a house was built? Note this is a regression ML model, not a classifier. Report appropriate evaluation metrics for the model. Explain the model and the evaluation metrics you used to determine if the model is good.

Here I used the random forest regression model. A regression model has the capability to give a non-binary answer, whereas a classification model will always return a binary result. We can see, based off the evaluation metrics, that the mean absolute error is just 6.4 years, which is not bad. We can also tell that we don't have very many outliers, because the root mean squared error is only 13 years. And just a general accuracy measurement, that's what r-squared is for. This one comes in at 87.8% accurate. 

```{python}
# This is what we are trying to predict
training = 'yrbuilt'

y = df_joined.select(training)

# drop the strings and y and before 1980
x = df_joined.drop([training, 'parcel', 'before1980'])


# Split the data for training and testing accuracy
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)


regressor = RandomForestRegressor()

regressor.fit(x_train, y_train)

pred = regressor.predict(x_test)
```

```{python}
print("Mean Absolute Error:", mean_absolute_error(y_test, pred))
print("Mean Squared Error:", mean_squared_error(y_test, pred))
print("Root Mean Squared Error:", root_mean_squared_error(y_test, pred))
print("R-squared:", r2_score(y_test, pred))
```
