---
title: "Client Report - Flights: Column Aggregation"
subtitle: "Unit 2 Task 2"
author: "Justin Hair"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```


## QUESTION 1

__Calculate the sample size (i.e. number of rows in the dataset) for each airport in each year__. What do you notice?

The sample size changes for airport between years by smaller values, it varies by about 1-2 rows for most airports. I also noticed that the sample size's mean is about 10, just by looking at the data.


```{python}
# display(df.height)

Q1 = df.group_by(["airport_name", "year"]).agg(pl.len().alias('sample_size'))

display(Q1)
```

## QUESTION 2

__Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

I chose to sort the airports by the percentage of flights that are delayed. Turns out that the worst airport by this deffinition is San Francisco in CA. 26.1% of flights are delayed. Thats about 1 in 4 flights which is crazy. 
Although I will note that the average delay time is less at the San Francisco airport than the other airports. 

```{python}
"""
Todo:
- group by airport name
- sum up the total flights and make it a column
- sum up total minutes delayed and make it a column
- create a new column for a porportion using (minutes delayed/total flights)
- sort from highest to lowest using that new column
"""


Q2 = (
    df.group_by("airport_code")
    .agg(
       # 2 columns created here
        pl.col("num_of_flights_total").sum().alias("total_flights"),
        pl.col("num_of_delays_total").sum().alias("total_delayed_flights"),

        # math done here  
        (pl.col("num_of_delays_total").sum() / pl.col("num_of_flights_total").sum()).alias("proportion_delayed"),
        (pl.col("minutes_delayed_total").sum() / pl.col("num_of_delays_total").sum() / 60).alias("average_delay_hours")
    )
    .sort("proportion_delayed", descending=True)
)

display(Q2)

```

## QUESTION 3

__Create a barplot showing the proportion of all flights that are delayed at each airport. Describe what you learn from this graph.__  

It turns out that SLC has the has the lowest proportion of delayed flights coming in at 14.6% which is 11.5% better then the worst airport. 
```{python}

(
  ggplot(data=Q2, mapping=aes(x="airport_code", y="proportion_delayed", fill="airport_code"))
  + geom_bar(stat="identity")
  + coord_flip()
  + labs(x="Airport", y="Proportion of delayed flights", fill="Airport Code")
)

```