---
title: "Client Report - Joins"
subtitle: "Unit 3 Task 3"
author: "Justin Hair"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = '/home/justin/Desktop/Spring-2026/DSE-250/DSE-250-Data-Science/Unit3-task1/InClass/lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query that pulls in the the salaries table and the collegeplaying table (and any other tables you might need) and store them in polars dataframes. In Python Polars, combine the dataframes to create a list of baseball players who attended BYU-Idaho. The new table should contain five columns: playerID, schoolID, salary, yearID and teamID associated with each salary.__

With these filters there are 15 records. (Only 2 different players)

```{python}
q1 = """
    SELECT 
      s.playerID, 
      s.salary,
      s.yearID, 
      s.teamID
    FROM salaries AS s
"""

q2 = """
    SELECT
      c.playerID,
      c.schoolID
    FROM collegeplaying AS c
"""

salaries = pl.read_database(q1, con)
college_playing = pl.read_database(q2, con)

players_from_byui = (
    college_playing
    .filter(pl.col("schoolID") == "idbyuid")
    .select("playerID", "schoolID")
    .unique()
)

df = salaries.join(players_from_byui, on="playerID", how="inner")

display(df.head(10))

```


## QUESTION 2

1. Pick any two baseball teams and compare them using a metric of your choice (average salary, home runs, number of wins, etc). Be creative! Write an SQL query to read in the table(s) you need, then use polars to manipulate the data. Finally, make a graph using Lets-Plot to visualize the comparison. What do you learn? 

I learned that if someone plays for the New York Yankees, they'll end up making on average, around $1.2 Million more then if they played for the Los Angeles Dodgers. I also learned that the Los Angeles Dodgers win more on average then the New York Yankees which makes sense why it pays more on average. More view, more money.

```{python}
# I couldnt name a single team so I used AI to pick two teams. I got Los Angeles Dodgers(LAN) and New York Yankees(NYA)
# It think it would be cool to see average salary for number of wins for both teams. (wins/salary)

q1 = """
    SELECT
      s.teamID,
      s.salary
    FROM salaries AS s
"""
q2 = """
    SELECT
      t.teamID,
      t.W
    FROM teams AS t
"""
salaries = pl.read_database(q1, con)
teams = pl.read_database(q2, con)

# display(salaries)
# display(teams)

df = salaries.join(teams, on="teamID", how="inner").group_by("teamID").agg(pl.col("salary").mean().alias("avg_salary"), pl.col("W").mean().alias("avg_wins")).with_columns((pl.col("avg_wins") / pl.col("avg_salary")).alias("wins_per_salary")).filter(pl.col("teamID").is_in(["LAN", "NYA"]))

display(df)


(
  ggplot(data=df, mapping=aes(x="avg_wins", y="avg_salary", color="teamID")) 
  + geom_bar(stat="identity")
)



```


