---
title: "Client Report - Baseball Database SQL Query"
subtitle: "Unit 3 Task 2"
author: "Justin Hair"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---


```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# I changed the path
sqlite_file = '../Unit3-task1/InClass/lahmansbaseballdb.sqlite'
# this path is relative to this .qmd file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query that provides playerID, yearID, and batting average for players with at least 1 at bat that year. Sort the table from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

Our top guy according to this data is aberal01. But when we use a search where ab >= 1 we honestly dont get good results. All top 5 people have the same score.

```{python}
# The code below can serve as a template for all the rest of your queries. It is just missing the
# SQL code. Put your SQL query in between the triple quotation marks to create the query. The records will be stored in 'results', which is a polars data frame

q = """
    SELECT 
      playerID, 
      yearID, 
      CAST(H AS REAL) / AB AS "batting_average"
    FROM Batting                                    -- pull from this part of the database
    WHERE AB >= 1                                   -- This keeps only player with >= 1 bats
    ORDER BY "batting_average" DESC, playerID ASC   -- This sorts it
    LIMIT 5                                         -- This only show highest 5
"""
result = pl.read_database(q, con)
display(result)


```


## QUESTION 2

__Use the same query as above, but only include players with at least 10 at bats that year. Print the top 5 results.__  

There we go. This is much higher quaility data. We can now see that nymanny01 is the best when it comes to these filters. 
```{python}
# Include and execute your code here

q = """
    SELECT 
      playerID, 
      yearID, 
      CAST(H AS REAL) / AB AS "batting_average"
    FROM Batting                                    -- pull from this part of the database
    WHERE AB >= 10                                   -- This keeps only player with >= 10 bats
    ORDER BY "batting_average" DESC, playerID ASC   -- This sorts it
    LIMIT 5                                         -- This only show highest 5
"""
result = pl.read_database(q, con)
result
```


## QUESTION 3

__Now modify the SQL query to calculate the batting average for players over their entire careers (all years combined). Only include players with at least 100 at bats over their entire career, and print the top 5 results.__

The best of all time was hazlebo01 with a batting average of 40.3% 

```{python}
# Include and execute your code here

q = """
    SELECT 
      playerID, 
      yearID, 
      CAST(SUM(H) AS REAL) / SUM(AB) AS "batting_average"
    FROM Batting                                    -- pull from this part of the database
    WHERE AB >= 100                                   -- This keeps only player with >= 100 bats
      GROUP BY playerID
    ORDER BY "batting_average" DESC, playerID ASC   -- This sorts it
    LIMIT 5                                         -- This only show highest 5
"""
result = pl.read_database(q, con)
result
```